sonar.projectKey=opensalestax-square
sonar.projectName=opensalestax-square
sonar.projectVersion=0.1.0-alpha.1

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/tools/**
sonar.test.inclusions=tests/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.host.url=http://10.32.161.205:9000
